# Generated by Django 4.2.16 on 2024-11-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player_id", models.IntegerField()),
                ("first_name", models.TextField()),
                ("last_name", models.TextField()),
                ("birthday", models.DateField()),
                ("country", models.TextField()),
                ("school", models.TextField()),
                ("position", models.TextField()),
                ("height", models.TextField()),
                ("weight", models.IntegerField()),
                ("draft_year", models.IntegerField()),
                ("draft_round", models.IntegerField()),
                ("draft_number", models.IntegerField()),
            ],
        ),
    ]
