# Generated by Django 4.2.16 on 2024-11-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nba", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="draft_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="draft_round",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
