# Generated by Django 4.2.16 on 2024-11-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nba", "0004_dreamteam_review_ranking"),
    ]

    operations = [
        migrations.AddField(
            model_name="dreamteam",
            name="name",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
